window.INSIGHTS = [
{
  "id": "25-tahun-selepas-9-11-drone-ai-keganasan",
  "title": "25 TAHUN SELEPAS 9/11: BILA DRONE DAN AI MENGUBAH WAJAH KEGANASAN",
  "excerpt": "Dua puluh lima tahun selepas 9/11, drone murah, AI dan infrastruktur digital mengubah ancaman keganasan. Mengapa serangan masa depan mungkin lebih sukar dihentikan?",
  "tags": [
    "Keselamatan",
    "Teknologi",
    "Geopolitik"
  ],
  "body": [
    "Kategori: Keselamatan | Teknologi | Geopolitik",
    "Tarikh: 6 September 2026",
    "Masa: 7:26 malam MYT",
    "Anggaran masa bacaan: 8–10 minit",
    "Artikel ini diadaptasi dan dianalisis berdasarkan tulisan Tom O’Connor, “Living on the Edge”, dalam Newsweek International edisi 11–18 September 2026. Edisi tersebut direkodkan dikeluarkan pada 4 September 2026, manakala versi digital menyatakan masa bacaan asal sekitar 16 minit.",
    "## Ancaman hari ini tidak semestinya datang daripada senjata canggih",
    "Dua puluh lima tahun selepas serangan 11 September 2001, dunia berdepan satu paradoks keselamatan yang semakin sukar: teknologi menjadikan kehidupan manusia lebih mudah, tetapi pada masa yang sama menjadikan keupayaan untuk melakukan keganasan lebih mudah dicapai.",
    "Serangan 9/11 sendiri memberi satu pengajaran penting. Operasi yang dilakukan oleh 19 anggota Al-Qaeda tidak bergantung kepada senjata futuristik. Antara alat penting yang digunakan untuk merampas pesawat ialah box cutter — pisau pemotong kecil yang pada asalnya merupakan alat biasa. Pengajaran utamanya ialah serangan berskala besar tidak semestinya memerlukan teknologi tentera yang mahal. Ia memerlukan perancangan, keazaman dan kemampuan mengenal pasti kelemahan dalam sistem yang sedia ada.",
    "Hari ini prinsip itu masih sama. Bezanya, “alat biasa” yang tersedia kepada orang awam jauh lebih berkuasa berbanding pada tahun 2001.",
    "Drone komersial, kecerdasan buatan atau AI (artificial intelligence — sistem komputer yang boleh melakukan tugas yang biasanya memerlukan kecerdasan manusia), komunikasi terenkripsi dan platform media sosial semuanya mempunyai kegunaan sah. Tetapi teknologi yang sama boleh disalahgunakan.",
    "## “Democratisation of destruction”",
    "Pakar keselamatan antarabangsa Kerry Chávez menggunakan satu ungkapan yang sangat menarik: democratisation of destruction — secara mudahnya, keupayaan untuk menghasilkan kemusnahan yang dahulunya hampir dimonopoli oleh negara dan tentera kini semakin boleh dicapai oleh kumpulan kecil atau individu.",
    "Menurut Chávez, perubahan terbesar bukanlah satu teknologi tertentu. Perubahan sebenarnya berlaku pada akses. Drone dan AI yang dahulu mahal, kompleks atau sukar diperoleh kini semakin murah dan tersedia secara komersial. Ini merendahkan entry threshold (halangan minimum untuk seseorang memasuki sesuatu bidang atau memperoleh sesuatu keupayaan) bagi kumpulan militan.",
    "Inilah perkara yang menjadikan ancaman moden bersifat asymmetric (tidak seimbang).",
    "Sebuah drone murah mungkin bernilai hanya beberapa ribu dolar. Tetapi untuk memintasnya, sebuah negara mungkin perlu menggunakan radar, sistem peperangan elektronik atau peluru berpandu bernilai ratusan ribu hingga jutaan dolar.",
    "Dalam erti kata lain, kos menyerang boleh menjadi murah, tetapi kos mempertahankan diri boleh menjadi sangat mahal.",
    "## ISIS memahami perubahan ini lebih awal",
    "Antara organisasi militan yang paling cepat memahami potensi teknologi ialah ISIS.",
    "Apabila drone kecil dan murah mula berkembang sekitar 2013, ISIS mengubah quadcopter komersial kepada alat peninjauan, pembawa bahan letupan dan juga instrumen propaganda. Rakaman serangan kemudian diedarkan di media sosial untuk menghasilkan kesan psikologi yang lebih besar.",
    "Namun inovasi ISIS yang mungkin lebih penting bukan drone, tetapi media sosial.",
    "Bruce Hoffman, pakar kontrakeganasan di Council on Foreign Relations, memberitahu Newsweek bahawa ISIS menjadi organisasi pengganas pertama yang benar-benar bersifat antarabangsa, dengan kira-kira 53,000 pejuang asing dari sekitar 80 negara direkrut ke dalam rangkaiannya. Media sosial membolehkan propaganda, perekrutan dan kutipan dana dilakukan merentas sempadan pada skala yang sukar dibayangkan oleh organisasi militan generasi sebelum itu.",
    "Walaupun “khalifah” wilayah ISIS di Iraq dan Syria tumbang menjelang 2019, organisasinya tidak hilang. Rangkaian dan sel bawah tanah terus beroperasi, termasuk ISIS-K di Afghanistan serta cabang-cabangnya di Afrika.",
    "Ini menunjukkan bahawa mengalahkan sebuah organisasi secara ketenteraan tidak semestinya menghapuskan ideologi, rangkaian atau kemahiran teknologinya.",
    "## Selepas media sosial, kini muncul AI",
    "Perubahan seterusnya mungkin lebih besar.",
    "ISIS dan penyokongnya telah mula bereksperimen dengan AI, termasuk penggunaan penyampai berita maya dan perbincangan mengenai cara mengatasi sekatan keselamatan model AI. Artikel Newsweek turut memetik contoh forum pro-ISIS yang membincangkan bagaimana model AI boleh “dijailbreak” — iaitu memintas perlindungan atau sekatan yang dipasang pada sistem AI.",
    "Perkara yang paling membimbangkan bukan sekadar AI menghasilkan propaganda.",
    "AI berpotensi mempercepat pencarian maklumat, penterjemahan, analisis data, koordinasi dan perancangan. Bruce Hoffman turut memberi amaran bahawa AI mungkin memendekkan R&D loop (kitaran penyelidikan dan pembangunan) bagi kumpulan yang cuba mendapatkan keupayaan kimia atau biologi.",
    "Ini tidak bermaksud seseorang hanya boleh bertanya kepada chatbot lalu memperoleh “senjata”. Sistem moden mempunyai perlindungan keselamatan. Tetapi persoalan keselamatan yang lebih besar ialah apa yang berlaku apabila teknologi yang semakin berkuasa digabungkan dengan data terbuka, kemahiran manusia dan sistem lain.",
    "## Ukraine menjadi sekolah peperangan drone",
    "Perang Ukraine pula mempercepat satu lagi perubahan: penyebaran kemahiran mengendalikan drone.",
    "Dalam perang tersebut, drone bukan lagi alat sampingan. Ia digunakan untuk peninjauan, serangan satu hala, penghantaran bahan letupan dan pengesanan sasaran. Rusia dan Ukraine juga sentiasa mencari teknologi baharu untuk mengatasi sistem pertahanan lawan.",
    "Carl Peterson dari Militant Wire menyebut fenomena yang muncul daripada perang ini sebagai drone diaspora (penyebaran manusia, kemahiran dan pengalaman peperangan drone dari satu medan perang ke tempat lain).",
    "Kebimbangannya mudah difahami. Ribuan warga asing telah melalui kawasan perang Ukraine. Sebahagian kembali ke negara masing-masing dengan pengalaman praktikal yang suatu ketika dahulu hanya dimiliki unit tentera khusus.",
    "Menurut laporan Newsweek, terdapat juga kes individu yang dikaitkan dengan organisasi jenayah rentas negara, termasuk kartel dadah, cuba mendapatkan pengalaman atau kemahiran drone melalui konflik tersebut.",
    "Teknologi tidak mempunyai ideologi. Kemahiran yang dipelajari untuk mempertahankan sebuah negara hari ini boleh digunakan untuk tujuan yang sangat berbeza esok.",
    "## Masalah sebenar ialah jumlah sasaran yang semakin banyak",
    "Ancaman teknologi baharu bukan hanya kerana penyerang mempunyai alat lebih canggih.",
    "Masyarakat moden sendiri telah menjadi lebih mudah terganggu.",
    "Elektrik, sistem pembayaran, internet, komunikasi, hospital, kilang semikonduktor, kabel dasar laut dan rantaian bekalan saling bergantung antara satu sama lain.",
    "Ini dipanggil interdependent infrastructure (infrastruktur yang saling bergantung).",
    "Bayangkan gangguan elektrik yang panjang dalam masyarakat hampir tanpa tunai. Masalahnya bukan sekadar lampu terpadam. Pembayaran elektronik boleh gagal, pam minyak mungkin terganggu, komunikasi menjadi sukar dan orang ramai mungkin menghadapi masalah membeli makanan atau ubat.",
    "Sebab itu istilah critical infrastructure (infrastruktur kritikal — sistem yang sangat penting kepada fungsi negara dan masyarakat) semakin menjadi pusat perbincangan keselamatan.",
    "Dalam abad ke-21, “sasaran” bukan lagi semata-mata bangunan kerajaan atau pangkalan tentera. Sebuah pelayan komputer, kabel komunikasi, pusat data atau loji kimia boleh menjadi sasaran strategik.",
    "## Drone swarm mungkin menjadi “WMD” baharu",
    "Zachary Kallenborn dari King’s College London mengemukakan satu idea yang lebih provokatif: serangan drone swarm (sekumpulan besar drone yang beroperasi serentak) mungkin suatu hari nanti perlu difikirkan seperti bentuk baharu WMD, weapons of mass destruction (senjata pemusnah besar-besaran).",
    "Senjata kimia, biologi, radiologi dan nuklear masih sukar diperoleh kerana memerlukan kepakaran, bahan tertentu dan kos yang tinggi.",
    "Tetapi bagaimana jika beratus-ratus atau beribu-ribu sistem murah dapat menyerang secara serentak?",
    "Lebih sukar lagi sekiranya AI digunakan untuk membantu navigasi, koordinasi atau pengenalpastian sasaran.",
    "Hoffman memberi amaran bahawa gabungan taktik serangan beramai-ramai, drone dan AI dalam kawasan bandar boleh menjadi amat sukar untuk dicegah atau dipertahankan.",
    "## Kerajaan pula berdepan perlumbaan yang mahal",
    "FBI memberitahu Newsweek bahawa selepas 9/11, agensi itu mengubah pendekatannya daripada sekadar menyiasat selepas kejadian kepada pengumpulan risikan untuk mengesan rancangan serangan lebih awal.",
    "Kini FBI turut mempunyai misi khusus Counter-UAS (usaha mengesan, menjejak dan mengurangkan ancaman sistem udara tanpa pemandu).",
    "Menurut angka yang FBI berikan kepada Newsweek, sejak bermulanya pentadbiran Trump kedua, agensi itu melaporkan 1,145 tangkapan subjek berkaitan kontrakeganasan dan lebih 1,097 gangguan operasi. Angka tersebut perlu dibaca sebagai statistik yang dibekalkan sendiri oleh FBI kepada penerbitan tersebut, bukannya ukuran bebas terhadap keberkesanan dasar kerajaan.",
    "Ini penting kerana sebahagian artikel Newsweek turut memuatkan kenyataan politik daripada jurucakap Department of Homeland Security mengenai pentadbiran Biden dan Trump. Kenyataan seperti itu wajar dibezakan daripada analisis teknikal pakar; ia adalah pandangan dan framing (cara sesuatu isu dibingkaikan) oleh pihak pentadbiran yang bercakap.",
    "## Ancaman terbesar mungkin bukan teknologi",
    "Bahagian paling menarik dalam perbincangan ini sebenarnya membawa kita kembali kepada 1914.",
    "Kallenborn mengingatkan bahawa dua peluru yang membunuh Archduke Franz Ferdinand bukanlah “senjata pemusnah besar-besaran”. Tetapi pembunuhan itu membantu mencetuskan rangkaian peristiwa yang membawa kepada Perang Dunia Pertama dan kematian berjuta-juta manusia.",
    "Maksudnya, kesan sebuah tindakan keganasan tidak boleh diukur hanya melalui jumlah mangsa pada hari serangan berlaku.",
    "Serangan boleh mencetuskan perang, ketakutan, perubahan undang-undang, polarisasi politik, tindakan balas dan konflik yang jauh lebih besar.",
    "Dalam konteks itu, teknologi hanyalah force multiplier (alat yang menggandakan kemampuan seseorang atau organisasi).",
    "Persoalan yang lebih penting ialah siapa yang menggunakannya, untuk tujuan apa, dan bagaimana sebuah masyarakat bertindak balas selepas serangan berlaku.",
    "## 25 tahun kemudian, pengajaran 9/11 masih sama",
    "Ada satu ironi besar di sini.",
    "Dua puluh lima tahun lalu, 9/11 menunjukkan bahawa alat yang sangat biasa boleh digunakan untuk menghasilkan kesan luar biasa jika kelemahan sistem berjaya dieksploitasi.",
    "Hari ini, prinsip itu tidak berubah.",
    "Yang berubah ialah kekuatan alat tersebut.",
    "Drone semakin murah. AI semakin pintar. Komunikasi semakin pantas. Maklumat semakin terbuka. Infrastruktur pula semakin digital dan saling bergantung.",
    "Jadi cabaran kontrakeganasan masa depan bukan sekadar mencari “pengganas seterusnya”.",
    "Ia adalah perlumbaan untuk memastikan teknologi yang meningkatkan kemampuan masyarakat tidak pada masa yang sama memberi penyerang kelebihan yang terlalu besar.",
    "Dan mungkin inilah persoalan paling penting selepas 25 tahun 9/11:",
    "Bolehkah sebuah masyarakat terus menikmati teknologi yang semakin terbuka dan berkuasa tanpa menjadikan dirinya semakin mudah dieksploitasi?",
    "## Rujukan",
    "1. Tom O’Connor, “Living on the Edge,” Newsweek International, edisi 11–18 September 2026, Pocketmags, masa bacaan asal 16 minit.",
    "2. Newsweek International, September 11–18, 2026, Newsweek Publishing LLC; tarikh keluaran digital direkodkan 4 September 2026, OverDrive.",
    "3. Salinan digital artikel yang sama turut disenaraikan oleh Pocketmags sebagai ciri utama kategori Security, mengesahkan tajuk, penulis dan edisi penerbitan.",
    "Cadangan tajuk SEO: 25 Tahun Selepas 9/11: Bagaimana Drone dan AI Mengubah Ancaman Keganasan",
    "Meta description: Dua puluh lima tahun selepas 9/11, drone murah, AI dan infrastruktur digital mengubah ancaman keganasan. Mengapa serangan masa depan mungkin lebih sukar dihentikan?",
    "Slug: 25-tahun-selepas-9-11-drone-ai-keganasan"
  ],
  "fullPage": true,
  "publishedAt": "2026-09-06",
  "publicationHash": "2c6efe32a93361b821eca0d735e948467cb555109335515d3d2334117aab0976",
  "image": "assets/25-tahun-selepas-9-11-drone-ai-keganasan-2c6efe32a93361b8.jpg"
},
{
  "id": "lord-of-the-flies-bila-fear-mengalahkan-reason",
  "image": "assets/lord-of-the-flies.png",
  "title": "LORD OF THE FLIES: BILA FEAR MENGALAHKAN REASON",
  "excerpt": "Ralph memimpin melalui consent. Jack memimpin melalui fear. Catatan tentang kuasa, demokrasi dan betapa nipisnya lapisan civilised society.",
  "publishedAt": "2026-09-06",
  "tags": [
    "Books",
    "Power",
    "Society"
  ],
  "fullPage": true,
  "body": [
    "Aku tengah baca <em>Lord of the Flies</em> karya William Golding. Buku lama, tapi ceritanya terasa sangat moden.",
    "Sekumpulan budak terdampar di sebuah pulau. Tiada orang dewasa. Tiada polis. Tiada kerajaan. Tiada siapa nak suruh mereka ikut peraturan.",
    "Pada awalnya, Ralph dipilih sebagai ketua.",
    "Dia cuba buat benda secara demokratik — mesyuarat, peraturan, pembahagian tugas, bina tempat perlindungan dan menjaga api supaya kapal boleh nampak mereka.",
    "<strong>Conch shell</strong> pula jadi simbol bahawa semua orang ada hak untuk bersuara.",
    "Very civilised.",
    "Kemudian muncul Jack.",
    "Jack tak begitu berminat nak bincang panjang. Dia faham satu benda yang lebih primal:",
    "<blockquote class=\"pull-quote\"><p><strong>manusia mudah dikawal apabila mereka takut.</strong></p></blockquote>",
    "Ada “beast” dalam hutan?",
    "Jack akan lindungi kau.",
    "Nak makan daging?",
    "Ikut kumpulan Jack.",
    "Nak rasa kuat, diterima dan jadi sebahagian daripada sesuatu?",
    "<strong>Join the tribe.</strong>",
    "Sedikit demi sedikit, politik pulau itu berubah.",
    "Daripada:",
    "<strong>“Apa yang baik untuk kita semua?”</strong>",
    "kepada:",
    "<strong>“Siapa yang boleh lindungi aku?”</strong>",
    "Dan di situlah Golding punya point kena tepat.",
    "Ralph memimpin melalui <strong>consent</strong> — orang ikut kerana mereka bersetuju.",
    "Jack memimpin melalui <strong>fear</strong> — orang ikut kerana mereka takut.",
    "Masalahnya, demokrasi perlukan disiplin.",
    "Perlu sabar.",
    "Perlu orang sanggup dengar pendapat yang mereka tak suka.",
    "Perlu orang menghormati peraturan walaupun peraturan itu kadang-kadang menyusahkan mereka.",
    "Authoritarianism pula kadang-kadang nampak lebih mudah.",
    "Tak perlu debat.",
    "Tak perlu tunggu undian.",
    "Tak perlu fikir terlalu banyak.",
    "<strong>Just follow the leader.</strong>",
    "Dan bila masyarakat mula takut, pemimpin yang menjanjikan keselamatan selalunya nampak lebih menarik daripada pemimpin yang meminta mereka berfikir.",
    "Itu yang berlaku kepada Jack.",
    "Dia bukan sekadar menawarkan perlindungan.",
    "Dia menawarkan identiti.",
    "Makanan.",
    "Keseronokan.",
    "Kekuatan.",
    "Dan paling penting — rasa bahawa mereka berada di pihak yang kuat.",
    "Bila Piggy mati dan conch pecah, bagi aku itu bukan sekadar satu babak ganas.",
    "Piggy mewakili <strong>reason</strong> — akal, logik dan pemikiran rasional.",
    "Conch pula mewakili <strong>rules, democracy and civilisation</strong>.",
    "Bila kedua-duanya hilang, yang tinggal hanyalah kekuatan, ketakutan dan siapa yang paling ganas.",
    "Dan dari situ, budak-budak itu bukan lagi sebuah community.",
    "Mereka sudah menjadi tribe.",
    "<strong>That’s pretty punk, actually.</strong>",
    "Bukan sebab punk bermaksud chaos.",
    "Bagi aku, semangat punk yang sebenar selalu ada persoalan terhadap kuasa.",
    "Siapa yang pegang kuasa?",
    "Kenapa kita ikut dia?",
    "Siapa yang bagi dia kuasa?",
    "Adakah kita ikut kerana kita percaya…",
    "atau kerana kita takut?",
    "<em>Lord of the Flies</em> akhirnya bukan sangat cerita tentang sekumpulan budak liar di sebuah pulau.",
    "Ia cerita tentang kita.",
    "Tentang betapa nipisnya lapisan yang kita panggil <strong>“civilised society.”</strong>",
    "Selagi keadaan stabil, semua orang boleh bercakap tentang nilai, demokrasi, peraturan dan toleransi.",
    "Tetapi apabila manusia mula takut, marah dan rasa terancam, semuanya boleh berubah dengan sangat cepat.",
    "Orang mula mencari seseorang yang boleh beri jawapan mudah.",
    "Seseorang yang nampak kuat.",
    "Seseorang yang berani menunjuk siapa musuh.",
    "Seseorang yang berkata:",
    "<strong>“Ikut aku. Aku akan lindungi kau.”</strong>",
    "Dan di situlah fear mula mengalahkan reason.",
    "Ralph mahu bina <strong>community</strong>.",
    "Jack mahu bina <strong>tribe</strong>.",
    "Ralph perlukan orang berfikir.",
    "Jack cuma perlukan orang takut.",
    "Dan bila fear lebih kuat daripada reason, tribe biasanya menang.",
    "<strong>At least for a while.</strong>",
    "No gods. No masters.",
    "But maybe…",
    "<strong>keep the conch. 🤘📖</strong>"
  ]
},
  {
    id: "iran-2026-di-antara-dua-kejatuhan",
    title: "Iran 2026: Di Antara Dua Kejatuhan",
    excerpt: "Kadangkala, rakyat tidak mempertahankan sistem kerana mereka percaya padanya. Mereka bertahan kerana mereka takut pada apa yang datang selepasnya.",
    image: "assets/chaos.jpg",
    publishedAt: "2026-03-01",
    tags: ["Geopolitics", "Power", "Society"],
    body: [
      "Ada satu ilusi yang sering dipegang oleh dunia luar.",
      "Bahawa apabila rakyat tidak memberontak, itu bermakna mereka bersetuju.",
      "Tetapi realiti politik jarang semudah itu.",
      "Kadangkala, rakyat tidak bangkit bukan kerana mereka percaya pada sistem. Tetapi kerana mereka memahami kos kejatuhan sistem itu sendiri.",
      "Seorang rakyat Iran pernah menulis sesuatu yang sangat jujur.",
      "\"Situasi kami bukan lagi sekadar politik. Ia adalah eksistensial.\"",
      "Eksistensial bermaksud ia bukan lagi soal siapa memerintah. Ia soal sama ada realiti itu sendiri boleh terus bertahan.",
      "Selama beberapa dekad, Republik Islam Iran membina legitimasi melalui gabungan ideologi, kawalan, dan struktur kuasa yang tertutup.",
      "Tetapi legitimasi bukan sesuatu yang kekal.",
      "Ia wujud hanya selagi manusia percaya ia wujud.",
      "Dan apabila kepercayaan itu hilang, sistem itu masih boleh berdiri — tetapi ia berdiri dalam keadaan kosong.",
      "Kosong dari kepercayaan.",
      "Kosong dari makna.",
      "Kosong dari masa depan.",
      "Namun di sinilah paradoks sebenar bermula.",
      "Kerana walaupun ramai rakyat tidak lagi percaya pada sistem, mereka juga tidak semestinya mahu melihat sistem itu runtuh.",
      "Bukan kerana mereka menyokongnya.",
      "Tetapi kerana mereka telah melihat apa yang berlaku kepada negara lain apabila sistem runtuh secara tiba-tiba.",
      "Iraq.",
      "Libya.",
      "Syria.",
      "Afghanistan.",
      "Negara-negara yang dijanjikan kebebasan, tetapi menerima kekosongan.",
      "Dan kekosongan adalah bentuk ketidakstabilan yang paling berbahaya.",
      "Kerana kerajaan yang buruk masih boleh diramal.",
      "Tetapi ketiadaan kerajaan mencipta realiti di mana tiada siapa mengawal apa-apa.",
      "Inilah dilema sebenar rakyat Iran hari ini.",
      "Mereka hidup di antara dua ketakutan.",
      "Ketakutan terhadap sistem yang mereka tidak lagi percaya.",
      "Dan ketakutan terhadap dunia tanpa sistem langsung.",
      "Dalam teori politik, legitimasi adalah asas sebenar kuasa.",
      "Bukan senjata.",
      "Bukan tentera.",
      "Bukan propaganda.",
      "Tetapi kepercayaan.",
      "Apabila rakyat percaya sistem itu sah, kuasa menjadi stabil.",
      "Apabila kepercayaan itu hilang, sistem hanya bertahan melalui inertia dan ketakutan.",
      "Ia masih berdiri.",
      "Tetapi ia tidak lagi hidup.",
      "Masalahnya, sejarah menunjukkan bahawa kejatuhan sistem autoritarian jarang menghasilkan kestabilan serta-merta.",
      "Kadangkala, ia menghasilkan sesuatu yang lebih buruk.",
      "Kekosongan kuasa.",
      "Dan kekosongan kuasa jarang kekal kosong.",
      "Ia akan diisi.",
      "Sama ada oleh kuasa dalaman yang baru.",
      "Atau kuasa luar yang melihat peluang.",
      "Inilah sebabnya mengapa ramai rakyat Iran hari ini kelihatan senyap.",
      "Bukan kerana mereka bersetuju.",
      "Tetapi kerana mereka memahami risiko.",
      "Mereka tahu bahawa sistem ini sedang reput.",
      "Tetapi mereka juga tahu bahawa api di luar mungkin lebih berbahaya daripada rumah yang sedang runtuh.",
      "\"Kami tinggal di rumah yang kami benci,\" kata seorang rakyat Iran.",
      "\"Tetapi kami dikelilingi api yang kami lebih takut.\"",
      "Ini bukan tanda kesetiaan.",
      "Ini adalah tanda kesedaran sejarah.",
      "Kerana rakyat yang telah melihat kejatuhan negara lain memahami satu perkara:",
      "Bahawa kejatuhan sistem bukanlah akhir cerita.",
      "Ia hanyalah permulaan ketidakpastian.",
      "Dan dalam politik, ketidakpastian adalah bentuk kuasa yang paling tidak stabil.",
      "Masalah terbesar sistem autoritarian bukanlah apabila rakyat membencinya.",
      "Tetapi apabila rakyat berhenti mempercayainya.",
      "Akhirnya, persoalan sebenar bukanlah sama ada sistem ini akan berubah.",
      "Tetapi bagaimana ia akan berubah.",
      "Kerana semua sistem yang kehilangan legitimasi akhirnya akan menghadapi realiti.",
      "Sama ada melalui reformasi.",
      "Atau melalui kejatuhan.",
      "Dan sejarah menunjukkan bahawa sistem yang gagal berubah biasanya memilih jalan kedua."
    ]
  },
  {
    id: "iran-2026-kebangkitan",
    title: "Iran 2026: Kebangkitan Rakyat dan Kejatuhan Legitimasi",
    excerpt: "Kadang-kadang sebuah rejim tidak runtuh kerana senjata. Ia runtuh kerana rakyat berhenti mempercayainya.",
    image: "assets/uprising-og.jpg",
    publishedAt: "2026-02-15",
    tags: ["Geopolitics", "Economy", "Power", "Society"],
    body: [
      "## Iran 2026: Kebangkitan Rakyat dan Kejatuhan Legitimasi",
      "Ada satu titik dalam sejarah di mana kuasa masih wujud secara fizikal, tetapi sudah mati secara moral.",
      "Iran pada tahun 2026 mungkin sedang berdiri di titik itu.",
      "Secara rasmi, negara itu masih mempunyai kerajaan. Masih mempunyai tentera. Masih mempunyai institusi.",
      "Tetapi legitimasi bukan datang daripada kewujudan struktur. Ia datang daripada kepercayaan.",
      "Dan kepercayaan, apabila hilang, tidak boleh dipaksa kembali dengan kekerasan.",
      "⸻",
      "## Apabila Ekonomi Runtuh, Naratif Juga Runtuh",
      "Sejarah menunjukkan bahawa kebanyakan revolusi tidak bermula dengan ideologi.",
      "Ia bermula dengan ekonomi.",
      "Apabila mata wang kehilangan nilai, rakyat mula kehilangan masa depan.",
      "Apabila harga meningkat, rakyat mula mempersoalkan sistem.",
      "Apabila kehidupan menjadi mustahil, ketakutan terhadap kerajaan menjadi lebih kecil daripada ketakutan terhadap masa depan.",
      "Pada titik itu, kestabilan politik menjadi ilusi.",
      "Kerajaan mungkin masih berkuasa, tetapi ia sudah kehilangan asas sebenar kuasa: penerimaan rakyat.",
      "⸻",
      "## Kuasa Bergantung kepada Persepsi, Bukan Sekadar Kekerasan",
      "Setiap sistem autoritarian bergantung kepada satu ilusi asas:",
      "bahawa ia tidak boleh dicabar.",
      "Tetapi ilusi itu rapuh.",
      "Ia bergantung kepada persepsi kolektif.",
      "Apabila rakyat mula melihat bahawa orang lain juga berani bangkit, ketakutan mula pecah.",
      "Dan apabila ketakutan pecah, sistem mula retak.",
      "Kuasa fizikal masih wujud.",
      "Tetapi kuasa psikologi sudah hilang.",
      "⸻",
      "## Teknologi dan Paradoks Kawalan",
      "Dalam era moden, kerajaan cuba mengawal maklumat.",
      "Internet ditutup. Komunikasi diputuskan.",
      "Secara logik, ini bertujuan untuk memulihkan kawalan.",
      "Tetapi secara paradoks, ia juga memberi isyarat kelemahan.",
      "Kerajaan yang yakin tidak perlu menutup komunikasi.",
      "Kerajaan yang takut perlu melakukannya.",
      "Dan rakyat dapat membezakan antara kedua-duanya.",
      "⸻",
      "## Legitimasi adalah Mata Wang Politik yang Sebenar",
      "Ekonomi mempunyai mata wang.",
      "Politik juga mempunyai mata wang.",
      "Namanya legitimasi.",
      "Apabila legitimasi jatuh, kerajaan boleh terus wujud secara teknikal.",
      "Tetapi ia tidak lagi stabil secara sejarah.",
      "Ia menjadi struktur yang menunggu masa.",
      "Menunggu krisis seterusnya.",
      "Menunggu titik pecah seterusnya.",
      "Menunggu detik di mana sejarah bergerak lebih pantas daripada kuasa.",
      "⸻",
      "## Apa yang Iran Ajar kepada Dunia",
      "Iran bukan sekadar kisah tentang satu negara.",
      "Ia adalah cermin kepada semua sistem kuasa.",
      "Ia mengingatkan kita bahawa:",
      "kuasa boleh memaksa ketaatan,",
      "tetapi tidak boleh memaksa kepercayaan.",
      "Dan dalam jangka panjang, kepercayaan sentiasa lebih kuat daripada ketakutan.",
      "⸻",
      "## Kesimpulan",
      "Setiap rejim percaya ia akan kekal.",
      "Sejarah menunjukkan sebaliknya.",
      "Yang menentukan bukan kekuatan senjata.",
      "Tetapi kekuatan legitimasi.",
      "Dan legitimasi, apabila hilang, jarang kembali.",
      "Tonton video berkaitan: <a href='https://youtu.be/voQaxc5lpVY?si=l4uDLR4O111e48ux' target='_blank' rel='noopener noreferrer'>Tonton di YouTube</a>",
      "---",
      "### Tonton video (dalam halaman)",
      "<div class='yt-embed'><iframe src='https://www.youtube.com/embed/voQaxc5lpVY' title='YouTube video player' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share' allowfullscreen></iframe></div>",
      "---",
      "Kalau tulisan ini membuat kau berfikir, simpan dan kongsi. Kerana memahami kuasa adalah langkah pertama untuk memahami dunia."
    ]
  },
  {
    id: "kesatuan-dan-ai",
    title: "Kesatuan dan AI",
    image: "assets/kesatuan.jpg",
    tags: ["AI", "Labour", "Policy"],
    excerpt:
      "Perbincangan mengenai kecerdasan buatan (AI) kini tidak lagi terhad kepada dunia teknologi semata-mata. Ia telah menjadi isu dasar awam, ekonomi politik dan masa depan pekerjaan.",
    body: [
      "## Kesatuan dan AI",
      "### Menjual Kecerdasan Buatan kepada Kesatuan Sekerja",
      "Perbincangan mengenai kecerdasan buatan (AI) kini tidak lagi terhad kepada dunia teknologi semata-mata. Ia telah menjadi isu dasar awam, ekonomi politik dan masa depan pekerjaan. Di Britain, kerajaan Parti Buruh mengambil pendekatan yang luar biasa: meyakinkan kesatuan sekerja bahawa AI boleh selari dengan kepentingan pekerja, bukan sekadar alat majikan atau ancaman kepada pekerjaan.",
      "Artikel ini menghuraikan bagaimana AI cuba diposisikan sebagai rakan kepada kesatuan sekerja, serta risiko sebenar yang tersembunyi di sebalik naratif tersebut.",
      "⸻",
      "## AI dan Kebimbangan Pekerja Sektor Awam",
      "Kerajaan Parti Buruh menyedari bahawa penyokong teras mereka—terutamanya pekerja sektor awam dan ahli kesatuan sekerja—mempunyai kebimbangan besar terhadap AI. Teknologi ini dilihat berpotensi:",
      "• mengganggu rutin kerja,",
      "• mengubah struktur pekerjaan, dan",
      "• menggantikan tenaga manusia.",
      "Namun hujah kerajaan jelas. AI akan tetap wujud, sama ada diterima atau ditolak. Persoalan sebenar, menurut istilah parti tersebut, bukan sama ada AI patut digunakan, tetapi sama ada ia boleh “diselaraskan dengan kepentingan pekerja”. Parti Buruh berhujah bahawa AI sejajar dengan kepentingan buruh dalam tiga cara utama.",
      "⸻",
      "## Pertama: AI dan Pemulihan Profesionalisme Sektor Awam",
      "Ramai profesional sektor awam seperti doktor, pekerja sosial dan guru kini berasa tertekan kerana kerja mahir yang mereka latih bertahun-tahun telah dibanjiri birokrasi dan kerja pentadbiran. Masa yang sepatutnya digunakan untuk berkhidmat kepada masyarakat kini habis di hadapan borang, sistem dan laporan.",
      "Kerajaan melihat AI sebagai penyelesaian praktikal. Jika kerja kertas dan dokumentasi diserahkan kepada sistem automatik:",
      "• beban birokrasi dapat dikurangkan,",
      "• proses kerja dipercepat, dan",
      "• profesional boleh kembali fokus kepada manusia, bukan prosedur.",
      "Sebagai contoh, satu laporan kerajaan mencadangkan penggunaan AI untuk:",
      "• merekod nota kes pekerja sosial kanak-kanak, dan",
      "• memberikan panduan pantas berkaitan perundangan.",
      "Perdana Menteri Keir Starmer menyifatkan pendekatan ini sebagai satu paradoks yang positif apabila beliau berkata bahawa AI, walaupun kelihatan tidak berperikemanusiaan, sebenarnya boleh menjadikan kerja manusia lebih bermakna dan berteraskan hubungan sosial.",
      "⸻",
      "## Kedua: AI sebagai Alat Menyelamatkan Kepercayaan terhadap Negara",
      "Hujah kedua kerajaan bersifat lebih politik dan strategik. Jika birokrasi awam yang besar dan perlahan ini tidak diperbaiki, kegagalannya akan membuka ruang kepada naratif populis untuk memotong perkhidmatan awam secara drastik.",
      "Dalam konteks ini, AI dilihat sebagai alat untuk membuktikan bahawa negara masih mampu berfungsi dengan cekap. Kerajaan merujuk kepada sistem perancangan yang tersumbat sebagai contoh. Melalui penggunaan AI, alat seperti Extract dibangunkan untuk menukar peta lama berasaskan kertas kepada data digital yang boleh digunakan, dengan tujuan mempercepatkan proses permohonan.",
      "Di sini, AI bukan sekadar inovasi teknologi, tetapi alat mempertahankan legitimasi negara. Jika perkhidmatan awam gagal dimodenkan, kegagalan itu boleh dijadikan alasan oleh pihak seperti Reform UK untuk mengurangkan peranan kerajaan secara menyeluruh.",
      "⸻",
      "## Ketiga: AI dan Keadilan untuk Kelas Pekerja",
      "Parti Buruh juga menekankan bahawa AI boleh memberi manfaat yang lebih besar kepada pengundi kelas pekerja, kerana ia menyediakan perkhidmatan yang sebelum ini hanya mampu diakses oleh golongan berpendapatan tinggi.",
      "Contoh paling jelas ialah cadangan kerajaan untuk membangunkan tutor AI yang boleh memberikan sokongan pembelajaran secara tersuai kepada pelajar. Inisiatif ini sarat dengan mesej politik berkaitan kelas dan ketidaksamaan pendidikan.",
      "Program ini bertujuan untuk:",
      "\"meratakan peluang bagi mereka yang tidak mampu membayar guru tuisyen persendirian\"",
      "(\"level the playing field for those who cannot afford private tutors\")",
      "Dalam naratif ini, AI dipersembahkan bukan sebagai teknologi elit, tetapi sebagai alat keadilan sosial yang berpotensi mengurangkan jurang antara yang mampu dan tidak mampu.",
      "⸻",
      "## Sokongan Bersyarat daripada Kesatuan Sekerja",
      "Kesatuan sekerja tidak menolak AI secara mutlak. Trades Union Congress, sebagai badan payung kesatuan, menyokong penggunaan AI secara prinsip, tetapi dengan syarat yang jelas.",
      "Antara tuntutan utama mereka ialah:",
      "• pekerja mesti dilibatkan secara bermakna dalam pembangunan teknologi, dan",
      "• kontrak kerajaan hanya diberikan kepada firma yang mengiktiraf kesatuan sekerja.",
      "Kerajaan pula memberi jaminan bahawa aplikasi tutor AI tersebut akan bersifat dipimpin oleh guru, dan tidak akan menggantikan hubungan manusia yang menjadi asas pendidikan dan perkhidmatan awam.",
      "⸻",
      "## Pertarungan Sebenar Masih di Hadapan",
      "Semua hujah ini masih berada pada tahap AI sebagai pembantu kerja. Pertarungan sebenar akan bermula apabila AI bukan lagi menambah baik pekerjaan, tetapi mula menghapuskan pekerjaan.",
      "Kerajaan telah mengumumkan penubuhan satu unit khas untuk mengkaji kesan AI terhadap pasaran buruh, dengan janji untuk:",
      "\"melindungi komuniti daripada kesilapan perubahan industri pada masa lalu\".",
      "Namun, ini merupakan janji yang besar dan sukar untuk ditunaikan. Sejarah perubahan teknologi menunjukkan bahawa setiap gelombang inovasi hampir pasti melahirkan pihak yang terpinggir, walaupun niat asalnya adalah pembaikan.",
      "⸻",
      "## Kesimpulan",
      "Perdebatan mengenai AI dan kesatuan sekerja menunjukkan bahawa AI bukan isu teknologi semata-mata. Ia adalah ujian kepada dasar buruh, legitimasi politik dan keadilan ekonomi.",
      "Britain kini sedang menguji satu pendekatan baharu:",
      "AI + kesatuan sekerja + legitimasi politik.",
      "Kejayaan atau kegagalan pendekatan ini akhirnya bergantung kepada satu persoalan asas: siapa yang menanggung kos sebenar apabila teknologi mula menggantikan manusia.",
      "⸻",
      "## Rujukan",
      "O’Connor, J., & Lindzon, J. (2026). *Working more doesn’t make you more productive.* TIME International, United Kingdom.",
      "UK Government AI policy discussions and public-sector modernization initiatives.",
      "Trades Union Congress (TUC) statements on artificial intelligence and labour protections.",
      "⸻",
      "Kalau tulisan ini kena dengan keresahan kau, simpan dan kongsi. Dan teruskan baca catatan lain di Rebel Insight — sebab masa depan kerja bukan benda kecil."
    ]
  },
  {
    id: "produktiviti-jam-kerja",
    title: "Bekerja Lebih Lama Tidak Menjadikan Kita Lebih Produktif",
    image: "assets/kerja.jpg",
    tags: ["Productivity", "Work Culture", "Future of Work"],
    excerpt:
      "Masa bekerja yang panjang sering disamakan dengan dedikasi. Namun dalam ekonomi moden, produktiviti sebenar tidak lagi diukur melalui berapa lama kita bekerja — tetapi melalui nilai yang kita hasilkan.",
    body: [
      "## Mitos Lama: Jam Kerja Panjang = Pekerja Terbaik",

      "Pada masa lalu, pekerja yang menghabiskan paling banyak jam di tempat kerja sering dianggap sebagai pekerja paling bernilai dalam sesebuah organisasi. Namun, tanggapan ini tidak lagi semestinya benar. Dalam dunia hari ini, kecerdasan buatan (AI) sedang mengubah cara kita bekerja, dan gerakan minggu kerja empat hari semakin mendapat sokongan. Keadaan ini memaksa kita mengakui satu hakikat penting: bekerja lebih lama tidak semestinya menjadikan seseorang lebih produktif.",

      "## Dari Kilang ke Ekonomi Pengetahuan",

      "Bagi pekerja barisan pemasangan (assembly line) yang melakukan tugas sama berulang kali, bekerja lebih lama dahulu bermakna lebih banyak hasil dapat dikeluarkan. Tetapi dalam persekitaran kerja moden, terdapat banyak cara untuk “mengisi” masa bekerja, dan tidak semuanya menyumbang secara langsung kepada keuntungan atau nilai sebenar organisasi.",

      "Hakikatnya, ramai pekerja boleh kelihatan sibuk sepanjang hari tanpa menghasilkan kerja yang benar-benar bernilai. Masa mereka sering dihabiskan untuk membalas e-mel yang tidak penting atau menghadiri mesyuarat yang sebenarnya tidak perlu.",

      "## Masalah Ukuran Produktiviti Zaman Perindustrian",

      "Ramai pekerja hari ini tertekan akibat penggunaan ukuran produktiviti zaman perindustrian, iaitu menilai produktiviti dengan membahagikan hasil kerja kepada jumlah jam bekerja. Pendekatan ini tidak sesuai dengan ekonomi berasaskan pengetahuan.",

      "Apabila organisasi terlalu menekankan jam kerja berbanding hasil, pekerja berada di bawah tekanan berterusan untuk mengorbankan masa rehat dan cuti yang sepatutnya mereka nikmati, semata-mata untuk membuktikan kesetiaan dan komitmen.",

      "## “Performance Punishment” dan “Quiet Promotion”",

      "Pekerja yang menyiapkan tugasan dengan cepat selalunya tidak diberi ganjaran berupa masa lapang, sebaliknya diberikan lebih banyak kerja untuk mengisi masa yang dijimatkan. Fenomena ini dikenali sebagai “performance punishment” atau “quiet promotion”.",

      "Sebaliknya, rakan sekerja yang bekerja hingga lewat malam, hujung minggu atau waktu rehat tengah hari untuk menyiapkan jumlah kerja yang sama sering dilihat lebih berdedikasi. Mereka lebih mudah dipuji atau dinaikkan pangkat, walaupun hasil kerja sebenar adalah setara.",

      "## Tekanan Untuk Nampak Sibuk, Bukan Hasil Bernilai",

      "Dinamik ini mewujudkan budaya kerja yang menekankan penampilan sibuk berbanding penciptaan nilai. Menurut Atlassian – State of Teams Report 2024, sebanyak 65% pekerja berasaskan pengetahuan percaya bahawa membalas mesej dengan cepat lebih penting daripada membuat kemajuan terhadap keutamaan utama.",

      "Asana – Anatomy of Work Index mendapati bahawa secara purata setiap tahun:  ",
      "• 103 jam dihabiskan dalam mesyuarat yang tidak perlu  ",
      "• 209 jam digunakan untuk kerja berulang atau bertindih  ",
      "• 352 jam dihabiskan hanya untuk bercakap tentang kerja  ",

      "Akibatnya, 88% pekerja mengadu mereka ketinggalan dalam projek sensitif masa dan inisiatif utama.",

      "## Kesibukan Palsu Menghakis Produktiviti",

      "Ironinya, tekanan untuk kelihatan sibuk ini sebenarnya menghalang kerja sebenar daripada disiapkan. Fenomena yang digelar “performative busyness” ini menjejaskan produktiviti organisasi dan pada masa yang sama melemahkan kesejahteraan mental dan fizikal pekerja.",

      "## Mengapa Jam Kerja Masih Digunakan?",

      "Walaupun fokus kepada hasil lebih masuk akal, meninggalkan ukuran berasaskan jam kerja bukanlah mudah. Jam kerja mempunyai kelebihan kerana ia bersifat universal.",

      "## Perbandingan Jam Kerja Global",

      "Data menunjukkan bahawa jadual kerja berbeza-beza dengan ketara di seluruh dunia.",

      "• Peru: 2,263 jam setahun  ",
      "• Mexico: lebih 42 jam seminggu  ",
      "• Costa Rica: kira-kira 41 jam seminggu  ",

      "Sebaliknya:  ",
      "• Jerman: sekitar 25.5 jam seminggu  ",
      "• Denmark: 26.5 jam  ",
      "• Norway: sekitar 27 jam.",

      "## Jam Kerja, Kekayaan dan Daya Saing Negara",

      "Menurut International Institute for Management Development (IMD), negara dengan jam kerja panjang selalunya kurang kaya. Negara dengan jam kerja pendek pula sering berada pada kedudukan daya saing global yang lebih tinggi.",

      "## Menilai Semula Makna Produktiviti",

      "Sudah tiba masanya kita menilai semula apa yang dimaksudkan dengan produktiviti. Adakah organisasi benar-benar mengukur hasil, atau sekadar menghitung jam yang dihabiskan di tempat kerja?",

      "Dalam ekonomi yang semakin dipacu pengetahuan dan teknologi, keupayaan menghasilkan nilai jauh lebih penting daripada sekadar kelihatan sibuk.",

      "Teruskan mengikuti analisis, refleksi dan wacana dasar di laman ini untuk memahami masa depan kerja, ekonomi dan kesejahteraan manusia.",

      "## Rujukan",

      "O’Connor, J. & Lindzon, J. (2026). Working more doesn’t make you more productive. TIME International, United Kingdom."
    ]
  },
  {
    id: "gen-z-future-work",
    title: "Generasi Z dan Masa Depan Dunia Pekerjaan",
    image: "assets/genz.jpg",
    tags: ["Society", "Future of Work", "Generation Z"],
    excerpt:
      "Generasi Z sedang membentuk semula makna pekerjaan — daripada kestabilan kepada fleksibiliti, daripada hierarki kepada autonomi.",
    body: [
      "## Siapakah Generasi Z",

      "Generasi Z merujuk kepada golongan yang lahir sekitar akhir 1990-an hingga awal 2010-an. Mereka ialah **generasi digital-native** — membesar ketika Internet, telefon pintar dan media sosial sudah menjadi norma kehidupan.",

      "Teknologi bagi mereka bukan kelebihan. Ia adalah asas untuk belajar, bekerja dan berkomunikasi.",

      "## Kebangkitan Suara Anak Muda",

      "Dalam beberapa tahun kebelakangan ini, suara Generasi Z semakin ketara di ruang awam.",

      "Daripada protes pelajar hingga gerakan iklim, generasi ini menunjukkan bahawa mereka bukan sekadar pewaris masa depan — tetapi **aktif membentuknya**.",

      "## Cara Generasi Z Melihat Dunia Kerja",

      "Berbanding generasi terdahulu, Generasi Z lebih menghargai **fleksibiliti, autonomi dan makna** dalam kerjaya.",

      "Kerja bukan lagi sekadar sumber pendapatan. Ia mesti selari dengan nilai hidup dan kesejahteraan mental.",

      "Model kerja gig, remote dan hybrid semakin diterima kerana memberi mereka kawalan terhadap masa dan tenaga.",

      "## Cabaran Ekonomi yang Nyata",

      "Namun realitinya tidak mudah.",

      "Kos sara hidup meningkat. Pasaran kerja semakin kompetitif. Ditambah pula dengan kebangkitan AI yang mencetuskan persoalan tentang masa depan pekerjaan.",

      "Bagi ramai, memiliki rumah kini terasa seperti sasaran yang semakin jauh.",

      "## Generasi Z sebagai Kuasa Pengguna",

      "Walaupun berdepan tekanan ekonomi, Generasi Z muncul sebagai **kuasa pengguna baharu**.",

      "Mereka tidak mudah terpengaruh dengan jenama besar. Sebaliknya, mereka mencari keaslian, ketelusan dan nilai sebenar.",

      "Kesetiaan tidak dibeli melalui pemasaran — ia diperoleh melalui kepercayaan.",

      "## Tidak Semua Generasi Z Itu Sama",

      "Penting untuk difahami bahawa Generasi Z bukan kumpulan homogen.",

      "Latar belakang ekonomi, geografi dan akses peluang mencipta realiti hidup yang berbeza.",

      "Namun mereka berkongsi satu persamaan besar — hidup dalam aliran maklumat yang pantas.",

      "## Implikasi Kepada Organisasi",

      "Kehadiran generasi ini memaksa organisasi menilai semula cara mereka beroperasi.",

      "Model kerja terlalu rigid semakin kurang relevan.",

      "Organisasi yang gagal beradaptasi mungkin bukan sahaja kehilangan bakat — tetapi masa depan.",

      "## Kesimpulan",

      "Generasi Z bukan sekadar tenaga kerja baharu.",

      "Mereka adalah **agen perubahan**.",

      "Cara kita memahami dan bekerjasama dengan generasi ini hari ini akan menentukan bentuk dunia pekerjaan esok.",

      "---",

      "Jika tulisan ini membuatkan anda berfikir, terokai artikel lain di Rebel Insight untuk perspektif yang lebih mendalam."
    ]
  },
    {
    id: "ai-adaptif-01",
    title: "AI Takkan Ganti Software Engineer — Tapi Engineer Yang Guna AI Akan Ganti Mereka Yang Enggan Guna AI",
    tags: ["AI", "Strategy", "Future"],
    excerpt:
      "Setiap kali teknologi baru muncul, soalan yang sama akan timbul. Adakah mesin akan menggantikan manusia? Mungkin itu sebenarnya soalan yang salah.",
    body: [
      "Setiap kali teknologi baru muncul, soalan yang sama akan timbul. Adakah mesin akan menggantikan manusia?",
      "Mungkin itu sebenarnya soalan yang salah.",
      "Masalah sebenar bukan AI akan ambil kerja kita. Masalah sebenar ialah betapa cepatnya dunia berubah, dan betapa ramai yang masih selesa bergerak dengan cara lama.",
      "AI bukan sekadar alat untuk jadi lebih produktif. Ia mempercepatkan segala-galanya. Individu yang tahu menggunakannya akan bergerak jauh lebih laju daripada mereka yang masih menunggu keadaan kembali seperti biasa.",
      "Jurang masa depan mungkin bukan lagi antara manusia dan mesin. Jurang itu akan lebih jelas antara manusia yang adaptif dan manusia yang statik.",
      "Sejarah hampir selalu berpihak kepada mereka yang belajar lebih cepat daripada kadar perubahan. Kita sudah nampak corak ini sejak revolusi industri, kemudian internet, dan sekarang kecerdasan buatan.",
      "Teknologi jarang benar-benar menghapuskan manusia. Tetapi teknologi hampir selalu menggantikan mereka yang enggan berubah.",
      "Dalam dunia yang semakin dipacu AI, kelebihan terbesar mungkin bukan pengalaman bertahun-tahun. Yang lebih penting ialah keupayaan untuk belajar perkara baru, melepaskan cara lama, dan menyesuaikan diri dengan pantas.",
      "Jadi mungkin soalan yang patut kita tanya bukan sama ada AI akan menggantikan kita.",
      "Soalan yang lebih penting ialah, adakah kita bergerak cukup cepat untuk kekal relevan?",
    ],
  },
];
